### ISSUE TITLE
Download XML forms error

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-admin#6]
@wsalesky I get this error when I click the "Download XML" button on the person form:

> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> <exception>
> <path>/db/apps/srophe-admin/forms/services/submit.xql</path>
> <message>
> err:XPST0003 Syntax error within user defined function local:dispatch: unexpected token: count [at line 41, column 126]
> </message>
> </exception>

**Comment by wsalesky** [comment]
what browser?

**Comment by wsalesky** [comment]
I found the bug. Try now please.

**Comment by nathangibson** [comment]
Awesome, works now!
